title: The Upworthy Research Archive
logo: /assets/images/upworthy-archive-logo-orange-grey.png
cornelllogo: /assets/images/cornell-cals-logo.png
psulogo: /assets/images/psu-college-liberal-arts.png
theme: jekyll-theme-minimal
